name: Simple Workflow

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  
 
 
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        run: echo 'Récuperation du code source'
      - name: Checkout
      - uses: actions/checkout@v4.2.2
      - name: Check finished
        run: echo 'Vérification terminée'
