name: Simple Workflow

on: 
  schedule:
    - cron 0 1-23 * * *
  
  workflow_dispatch
 
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests on Java 8
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 8
          distribution: zulu
      - run: mvn -f pom.xml test
